# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-14 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intro',
            field=models.TextField(default='Intro will be here'),
            preserve_default=False,
        ),
    ]
