# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-27 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20160427_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
