# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-19 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='Introduction',
        ),
    ]
