# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-19 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20160519_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduction',
            name='excerpt',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='introduction',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
