# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-28 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20160519_1904'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Introduction',
        ),
    ]
